### ISSUE TITLE
Normalize batch s4 error

### ISSUE THREAD

**Issue by SteveBoothHLI** [MarioniLab/cydar#2]
Hi there, we have multiple batches of separately barcoded samples, so I am trying to normalize across all the samples/batches.

I tried the following to read all the fcs files into a single flowset and normalize, but I get an error.
Is there something obvious I am doing wrong? 
Thanks for your help!
Steve

```library(ncdfFlow)

fcs <- read.ncdfFlowSet(files = md$file_name)

corrected <- normalizeBatch(fcs, batch.comp = NULL, mode="range")

Error in as.list.default(X) : 
  no method for coercing this S4 class to a vector)```

**Comment by LTLA** [comment]
You probably want to format your comment better, use triple backticks and newlines.

The `normalizeBatch` documentation isn't as clear as it should be (and will be better in the next release), but the first argument should be a list of `ncdfFlowSet` objects. Each object in the list should correspond to a _single_ batch, and contain all samples from that batch. Your error is because you're giving a single `ncdfFlowSet` object to `normalizeBatch`, and the function is trying to treat it as a list... which it isn't.

Setting `batch.comp=NULL` assumes that the composition of each batch (in terms of the number of replicates for each condition, e.g., treated, untreated, knockout, wild-type) is the same. If that's not the case, you'll need to specify it manually, as discussed [here](https://support.bioconductor.org/p/120114/#120146).

**Comment by SteveBoothHLI** [comment]
Hi Aaron, thanks for your reply!

Based on your guidance I have successfully applied the normalization now. Sorry if this is a naive question but is there a way to write the normalized intensities back to fcs files? I'm trying to analyze differential cytokine expression using Catalyst and Diffcyt which start from fcs. import.

Thanks again,
Steve

**Comment by LTLA** [comment]
Try `write.FCS` from _flowCore_. It'll complain about being experimental but it seems to work correctly.
