### ISSUE TITLE
Estimating hyperspheres overlap

### ISSUE THREAD

**Issue by JHYSiu** [MarioniLab/cydar#5]
Is there a way to estimate how many hyperspheres overlap in both the significant as well as the non-significant hyperspheres, and if this is even across the dataset? Thanks!

**Comment by LTLA** [comment]
Hm. Estimating overlap is possible, but perhaps it would help to know the actual scientific question you want to answer. By default, the hyperspheres will certainly overlap (they're just constructed on every 10th cell or so) and the degree of overlap will definitely not be even across the dataset (more hyperspheres in denser regions of the expression space).

**Comment by JHYSiu** [comment]
It's to address a reviewer's comment tbh (see below). I think I will just quantify the abundance difference of certain phentoypes using a separate supervised method unless there's something else you suggest. :) 

"While this is an interesting approach it would be helpful to have some information about how identical cells are shared between different hyperspheres (one cell may belong to several hyperpheres and looking at the plots this might be frequent, but is this similarly frequent for all hyperpheres?)."

**Comment by LTLA** [comment]
I'm not sure why the reviewer wants to know this - a single cell may certainly contribute to multiple hyperspheres, which isn't a problem when we're trying to detect differentially abundant regions of space. If a cell is used in multiple hyperspheres, those hyperspheres must all be adjacent, so that cell is really just contributing a single count to the differential abundance inference for the same general region of space - no harm, no foul. (The spatial FDR handles the correlations in the multiple testing correction for overlapping hyperspheres, even when the frequency of overlaps differ between hyperspheres.)

If the reviewer remains unconvinced, your suggestion of using a supervised method sounds reasonable. I would suggest using the hyperspheres to help you define the appropriate gates on each population - I think `pickBestMarkers()` can do that for you - and then show that the abundance does indeed change in the selected region of the high-dimensional marker space.

**Comment by JHYSiu** [comment]
Great thanks especially for the sanity check!
